// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PubQuizMaster.Data;

#nullable disable

namespace PubQuizMaster.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260918002350_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PubQuizMaster.Core.Models.Content.Answer", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("QuestionIndex")
                        .HasColumnType("integer");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RecordedByScorerId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("RoundId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.HasIndex("RoundId", "TeamId", "QuestionIndex")
                        .IsUnique()
                        .HasDatabaseName("IX_Answers_RoundId_TeamId_QuestionIndex");

                    b.ToTable("Answers");
                });

            modelBuilder.Entity("PubQuizMaster.Core.Models.Event.Participant", b =>
                {
                    b.Property<Guid>("QuizId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsNonCompetitive")
                        .HasColumnType("boolean");

                    b.Property<int>("SheetOrder")
                        .HasColumnType("integer");

                    b.HasKey("QuizId", "TeamId");

                    b.HasIndex("TeamId");

                    b.ToTable("Participants");
                });

            modelBuilder.Entity("PubQuizMaster.Core.Models.Event.Quiz", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsLegacyImport")
                        .HasColumnType("boolean");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IsCompleted", "IsLegacyImport")
                        .IsUnique()
                        .HasDatabaseName("IX_Quizzes_SingleActive")
                        .HasFilter("\"IsCompleted\" = false AND \"IsLegacyImport\" = false");

                    b.ToTable("Quizzes");
                });

            modelBuilder.Entity("PubQuizMaster.Core.Models.Event.Round", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsFinal")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsFinalized")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("QuestionCount")
                        .HasColumnType("integer");

                    b.Property<Guid>("QuizId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("QuizId");

                    b.ToTable("Rounds");
                });

            modelBuilder.Entity("PubQuizMaster.Core.Models.Event.Scorer", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("RoundId")
                        .HasColumnType("uuid");

                    b.Property<string>("ScorerId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.PrimitiveCollection<List<Guid>>("TeamIds")
                        .IsRequired()
                        .HasColumnType("uuid[]");

                    b.HasKey("Id");

                    b.HasIndex("RoundId");

                    b.ToTable("Scorers");
                });

            modelBuilder.Entity("PubQuizMaster.Core.Models.Player.Result", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("QuizId")
                        .HasColumnType("uuid");

                    b.Property<int?>("Rank")
                        .HasColumnType("integer");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("TotalScore")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.HasIndex("QuizId", "TeamId")
                        .IsUnique()
                        .HasDatabaseName("IX_Scores_QuizId_TeamId");

                    b.ToTable("Scores");
                });

            modelBuilder.Entity("PubQuizMaster.Core.Models.Player.Team", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("IX_Teams_NormalizedName");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("PubQuizMaster.Core.Models.Content.Answer", b =>
                {
                    b.HasOne("PubQuizMaster.Core.Models.Event.Round", null)
                        .WithMany("Answers")
                        .HasForeignKey("RoundId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PubQuizMaster.Core.Models.Event.Participant", b =>
                {
                    b.HasOne("PubQuizMaster.Core.Models.Event.Quiz", "Quiz")
                        .WithMany("ParticipatingTeams")
                        .HasForeignKey("QuizId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PubQuizMaster.Core.Models.Player.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quiz");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("PubQuizMaster.Core.Models.Event.Round", b =>
                {
                    b.HasOne("PubQuizMaster.Core.Models.Event.Quiz", null)
                        .WithMany("Rounds")
                        .HasForeignKey("QuizId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PubQuizMaster.Core.Models.Event.Scorer", b =>
                {
                    b.HasOne("PubQuizMaster.Core.Models.Event.Round", null)
                        .WithMany("Assignments")
                        .HasForeignKey("RoundId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PubQuizMaster.Core.Models.Player.Result", b =>
                {
                    b.HasOne("PubQuizMaster.Core.Models.Event.Quiz", "Quiz")
                        .WithMany("Results")
                        .HasForeignKey("QuizId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PubQuizMaster.Core.Models.Player.Team", "Team")
                        .WithMany("Results")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quiz");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("PubQuizMaster.Core.Models.Event.Quiz", b =>
                {
                    b.Navigation("ParticipatingTeams");

                    b.Navigation("Results");

                    b.Navigation("Rounds");
                });

            modelBuilder.Entity("PubQuizMaster.Core.Models.Event.Round", b =>
                {
                    b.Navigation("Answers");

                    b.Navigation("Assignments");
                });

            modelBuilder.Entity("PubQuizMaster.Core.Models.Player.Team", b =>
                {
                    b.Navigation("Results");
                });
#pragma warning restore 612, 618
        }
    }
}
